export const FETCH_DATA_START = 'FETCH_TABLE_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_TABLE_DATA_FAILURE';
export const UPDATE_TABLE_DATA_FAILURE = 'UPDATE_TABLE_DATA_FAILURE';
export const UPDATE_TABLE_DATA_START = 'UPDATE_TABLE_DATA_START';
export const UPDATE_TABLE_DATA_SUCCESS = 'UPDATE_TABLE_DATA_SUCCESS';
